import Head from 'next/head'
import Card from '../components/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Samuel Angulo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1 className='container mx-auto p-8 text-[30px] font-bold'>Samuel's LinkTree</h1>
        </div>
        <section className='grid lg:grid-cols-4 md:grid-cols-2 gap-8 container mx-auto sm:p-8 md:p-0'>
        <Card link="https://github.com/mvmeo" titulo="GITHUB" color="bg-gray-700"/>
        <Card link="https://www.strava.com/athletes/100879125" titulo="STRAVA" color="bg-orange-400"/>
        <Card link="https://medium.com/@samuelangulo" titulo="MEDIUM (Blog)" color="bg-red-500"/>
        <Card link="https://twitter.com/sam_angulo_" titulo="TWITTER" color="bg-blue-500"/>
        </section>
        
      </main>
    </>
  )
}
